// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace P_Quiz
{
    [Table("ToDo", Schema = "quiz")]
    public partial class ToDo
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Task Title")]
        public string Title { get; set; }
        [Column("due", TypeName = "date")]
        public DateTime? Due { get; set; }
    }
}